version: '3.8'
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    restart: always
    ports:
      - "5173:5173"

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    restart: always
    ports:
      - "8080:8080"